### PR TITLE
Add Japanese Support

### PR DESCRIPTION
**Pull request by JonasGao**

### CODE REVIEW

**Comment by Kiana-Kaslana** [comment]
Then, what should I do^ - ^？

**Comment by JonasGao** [comment]
@Kiana-Kaslana OK, 🤣  , let me test... wait my answer

**Comment by Kiana-Kaslana** [comment]
うん、お願い^_−☆〜

**Comment by JonasGao** [comment]
@Kiana-Kaslana OK, i tested~~

**Comment by JonasGao** [comment]
@Kiana-Kaslana And! you must know.
My windows cant display japanese, i dont know why, maybe i must install "Windows Japan version".
So, I force change the variable "name" to "japan", to make it work.
So, I'm not sure it works fine on your computer

**Comment by JonasGao** [comment]
@Kiana-Kaslana Now, if you want to merge back. let`s do this

click it!



and click it!

**Comment by Kiana-Kaslana** [comment]
うん、分かりました。次は？^ - ^

**Comment by Kiana-Kaslana** [comment]
@JonasGao あの。。。貴方はこのバージョンを私に送ってくれますか？ちょっとテストして方がいいと思います。

**Comment by JonasGao** [comment]
Here ~ [Shadowsocks.exe.zip](https://github.com/Kiana-Kaslana/shadowsocks-windows/files/802939/Shadowsocks.exe.zip)

**Comment by Kiana-Kaslana** [comment]
でもね〜部分の翻訳は表示できません。(´Д` )

**Comment by JonasGao** [comment]
which part ~

**Comment by Kiana-Kaslana** [comment]
Edit Online PAC URL...
Scan QRcode from screen...
check for updates...

**Comment by JonasGao** [comment]
The content is not translated, because the keyword is wrong.
The correct keyword is "Edit Online PAC URL...", but you are "Edit Online PAC URL…"
=> "..." vs "…", it is different

**Comment by Kiana-Kaslana** [comment]
(´Д` )

**Comment by JonasGao** [comment]
I create pull request again ~ [there](https://github.com/Kiana-Kaslana/shadowsocks-windows/pull/2) merge and create pull request back to original project

**Pull request merged**
